import Link from "next/link";
import Image from "next/image";
import { ArrowRight, ArrowUpRight, Wine, GlassWater, PackageCheck, ListChecks, Layers, PartyPopper, UtensilsCrossed, Gift } from "lucide-react";
import { featuredProducts, products, occasions } from "@/lib/catalogue";
import { ProductCard, BottleIllustration } from "@/components/product-card";
export default function Home(){return <main id="main-content"><section className="hero"><div className="hero-copy"><p className="eyebrow">DWIN DISTRIBUTION · GHANA</p><h1>Premium drinks,<br/>supplied <em>properly.</em></h1><p className="hero-description">For the bottles you love and the occasions that matter. Discover wines, spirits and everyday refreshments for your home, business or next gathering.</p><div className="hero-actions"><Link className="primary-button" href="/list">Explore all products <ArrowUpRight size={18}/></Link><a className="text-link" href="#for-your-occasion">Find your occasion <ArrowRight size={16}/></a></div><div className="hero-proof"><span><b>{products.length.toLocaleString()}</b> products to explore</span><i/><span>One thoughtfully<br/>curated collection.</span></div></div><div className="hero-art"><Image src="/images/original/dwin-still-life.png" fill priority sizes="(max-width: 760px) 100vw, 55vw" alt="A considered drinks selection on warm stone, with wine, amber spirits and sparkling water"/><div className="hero-art-caption"><span>THE ART OF A GOOD SELECTION</span><span>01 — DWIN</span></div></div></section>
<section className="quick-links" aria-label="Explore a collection">{[['Spirits','spirits','Single malts to cocktail essentials'],['Wines & champagne','wines','Everyday favourites. Special vintages.'],['Non-alcoholic','non-alcoholic','Something for everyone.']].map(([name,key,copy],i)=><Link key={key} href={`/list?collection=${key}`}><span className="collection-icon">{i===2?<GlassWater/>:<Wine/>}</span><div><h2>{name}</h2><p>{copy}</p></div><ArrowUpRight size={21}/></Link>)}</section>
<section className="section shop-categories"><div className="section-heading"><div><p className="eyebrow">FIND YOUR FAVOURITES</p><h2>Good taste starts here.</h2></div><Link href="/list" className="text-link">All categories <ArrowRight size={17}/></Link></div><div className="category-grid">{[['WHISKY','Whisky','For a slower kind of evening.'],['WINE','Wine','A seat at every table.'],['CHAMPAGNE','Champagne','Make a moment of it.'],['NON ALCOHOLIC','Soft drinks & mixers','Refreshingly good company.']].map(([category,name,copy],i)=><Link key={category} className={`category-card category-tone-${i}`} href={`/list?category=${encodeURIComponent(category)}`}><div className="category-top"><span>0{i+1}</span><ArrowUpRight size={20}/></div><BottleIllustration category={category}/><div><h3>{name}</h3><p>{copy}</p></div></Link>)}</div></section>
<section className="section featured-section"><div className="section-heading"><div><p className="eyebrow">THE DWIN EDIT</p><h2>Worth making room for.</h2></div><Link href="/list" className="text-link">Discover the collection <ArrowRight size={17}/></Link></div><div className="featured-grid">{featuredProducts.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
<section className="occasion-section section" id="for-your-occasion"><div className="occasion-intro"><p className="eyebrow">MORE THAN A BOTTLE</p><h2>Whatever brings<br/>you together.</h2><p>A dinner for six or a room full of guests. Start with the occasion; we’ll help you build the selection.</p><span className="occasion-mark">D.</span></div><div className="occasion-links">{Object.entries(occasions).map(([key,item],i)=><Link href={`/list?occasion=${key}`} key={key}><span className="occasion-symbol">{i===0?<PartyPopper/>:i===1?<UtensilsCrossed/>:<Gift/>}</span><div><span className="eyebrow">0{i+1}</span><h3>{item.name}</h3><p>{item.copy}</p></div><ArrowUpRight size={22}/></Link>)}</div></section>
<section className="section brands-section"><p className="eyebrow">FAMILIAR NAMES. EXCEPTIONAL CHOICE.</p><div className="brand-list">{[['HENNESSY','Hennessy'],['MOET','MOËT & CHANDON'],['JOHNNIE WALKER','JOHNNIE WALKER'],['HENDRICK\'S GIN','HENDRICK’S'],['BAILEYS','BAILEYS'],['SAN PALLEGRINO','S.PELLEGRINO']].map(([brand,name])=><Link href={`/list?brand=${encodeURIComponent(brand)}`} key={brand}>{name}</Link>)}</div></section>
<section className="distribution-section"><div><p className="eyebrow">YOUR SELECTION. OUR BUSINESS.</p><h2>A better way<br/>to stock up.</h2><p>Bring your entire drinks list together with Dwin. Explore the range, choose your quantities and request a quote built around what you need.</p><Link href="/list" className="light-button">Build your order <ArrowUpRight size={18}/></Link></div><div className="value-list">{[[Layers,'A range that works together','From premium spirits and wine to water, mixers and coffee. One place to plan the whole selection.'],[ListChecks,'Your order, your way','Choose individual products, adjust quantities and keep your selection ready whenever you return.'],[PackageCheck,'Clarity before you commit','Request confirmation of prices, quantities, availability and delivery before placing an order.']].map(([Icon,title,copy])=>{const I=Icon as typeof Layers;return <div key={String(title)}><I size={25}/><div><h3>{String(title)}</h3><p>{String(copy)}</p></div></div>})}</div></section><section className="closing-cta"><p className="eyebrow">LET’S FIND YOUR NEXT FAVOURITE</p><h2>The whole collection.<br/>A world of possibilities.</h2><Link href="/list" className="primary-button">Shop all {products.length.toLocaleString()} products <ArrowRight size={18}/></Link></section></main>}
