"use client";
import Image from "next/image";
import { useState } from "react";
import { ArrowUpRight } from "lucide-react";
import { money, sizeLabel, titleCase, type Product } from "@/lib/catalogue";
import { Modal } from "./modal";
import { Quantity } from "./cart";
export function BottleIllustration({category}:{category:string}){
 const wine=['WINE','CHAMPAGNE','PROSECCO','SPARKLING WINE','VERMOUTH'].includes(category);const can=category==='NON ALCOHOLIC';const other=['COFFEE','TEA','MACHINES','DAIRY'].includes(category);
 return <svg className="bottle-illustration" viewBox="0 0 180 260" role="img" aria-label={`${titleCase(category)} category illustration`}><ellipse cx="90" cy="240" rx="43" ry="4" fill="#e0d8ca"/>{other?<><path d="M43 76H135L127 231H51Z" fill="#d9cbb7"/><path d="M43 76L55 52H124L135 76" fill="#a69c85"/><rect x="53" y="113" width="74" height="72" fill="#f7f3e9"/></>:can?<><rect x="49" y="47" width="82" height="188" rx="14" fill="#b5c0ae"/><ellipse cx="90" cy="48" rx="40" ry="7" fill="#d2d7ca"/><rect x="53" y="107" width="74" height="77" fill="#f7f3e9"/></>:<><path d={wine?'M76 28H104V82C104 98 124 108 124 134V228Q124 236 115 236H65Q56 236 56 228V134C56 108 76 98 76 82Z':'M74 29H106V87C106 102 137 107 137 130V221Q137 236 121 236H59Q43 236 43 221V130C43 107 74 102 74 87Z'} fill={wine?'#354738':'#986038'}/><rect x="73" y="24" width="34" height="28" rx="2" fill="#58252e"/><path d="M67 125H114V192H67Z" fill="#f7f3e9"/><path d="M65 115V213" stroke="#fff" strokeOpacity=".2" strokeWidth="4"/></>}<text x="90" y="151" textAnchor="middle" fontFamily="Georgia,serif" fontSize="30" fill="#602733">D</text><path d="M77 161H103" stroke="#b4935b"/><text x="90" y="174" textAnchor="middle" fontFamily="sans-serif" fontSize="5" letterSpacing="1" fill="#602733">SELECTION</text></svg>
}
export function ProductVisual({product}:{product:Product}){return product.image?<Image src={product.image} alt={titleCase(product.name)} fill sizes="(max-width: 600px) 45vw, (max-width: 1000px) 30vw, 25vw" className="packshot"/>:<BottleIllustration category={product.category}/>}
export function ProductCard({product}:{product:Product}){
 const [detail,setDetail]=useState(false);
 return <><article className="product-card"><button className="product-image" onClick={()=>setDetail(true)} aria-label={`View ${product.name}`}><ProductVisual product={product}/>{!product.image&&<span className="image-caption">Category illustration</span>}<span className="inspect-product"><ArrowUpRight size={17}/></span></button><div className="product-card-content"><div className="product-category">{titleCase(product.category)} <span>{sizeLabel(product.bottleMl)}</span></div><button className="product-title" onClick={()=>setDetail(true)}>{titleCase(product.name)}</button><p className="product-origin">{titleCase(product.region)}</p><div className="product-card-bottom"><strong><small>GHS</small> {money(product.price)}</strong><Quantity product={product}/></div></div></article>{detail&&<Modal title="The details" className="product-modal" onClose={()=>setDetail(false)}><div className="product-detail"><div className="detail-image"><ProductVisual product={product}/>{!product.image&&<span className="image-caption">Category illustration, not product photography</span>}</div><div><p className="eyebrow">{titleCase(product.category)}</p><h2>{titleCase(product.name)}</h2><strong className="detail-price">GHS {money(product.price)}</strong><dl><div><dt>Brand</dt><dd>{titleCase(product.brand)}</dd></div><div><dt>Country / region</dt><dd>{titleCase(product.region)}</dd></div><div><dt>Bottle size</dt><dd>{sizeLabel(product.bottleMl)}</dd></div>{product.size&&<div><dt>Original size field</dt><dd>{product.size}</dd></div>}{product.qty&&<div><dt>Pack quantity (source)</dt><dd>{product.qty}</dd></div>}{product.alc!==null&&product.alc>0&&<div><dt>Alcohol</dt><dd>{product.alc}%</dd></div>}<div><dt>Product code</dt><dd>{product.code}</dd></div>{product.status&&<div><dt>Catalogue update</dt><dd>{titleCase(product.status)}</dd></div>}</dl><p className="fine-print">Availability and pack configuration confirmed with your quote. {product.imageNote}</p><Quantity product={product}/></div></div></Modal>}</>;
}
