"use client";
import { useState } from "react";
import { money, sizeLabel, titleCase, type Product } from "@/lib/catalogue";
import { Modal } from "./modal";
import { Quantity } from "./cart";
export function ProductCard({product}:{product:Product}){
 const [detail,setDetail]=useState(false);
 return <><article className="price-row"><div className="price-row-name"><button className="price-name" onClick={()=>setDetail(true)} aria-label={`View details for ${product.name}`}>{product.name}</button><span className="price-row-category">{titleCase(product.category)}</span></div><span className="price-row-size">{product.bottleMl!==null?sizeLabel(product.bottleMl):"Size on enquiry"}</span><strong className="price-row-value"><small>GHS</small> {money(product.price)}</strong><div className="price-row-order"><Quantity product={product}/></div></article>{detail&&<Modal title="The details" className="product-modal" onClose={()=>setDetail(false)}><div className="product-detail text-product-detail"><div><p className="eyebrow">{titleCase(product.category)}</p><h2>{product.name}</h2><strong className="detail-price">GHS {money(product.price)}</strong><dl><div><dt>Brand</dt><dd>{titleCase(product.brand)}</dd></div><div><dt>Country / region</dt><dd>{titleCase(product.region)}</dd></div><div><dt>Bottle size</dt><dd>{sizeLabel(product.bottleMl)}</dd></div>{product.size&&<div><dt>Original size field</dt><dd>{product.size}</dd></div>}{product.qty&&<div><dt>Pack quantity (source)</dt><dd>{product.qty}</dd></div>}{product.alc!==null&&product.alc>0&&<div><dt>Alcohol</dt><dd>{product.alc}%</dd></div>}<div><dt>Product code</dt><dd>{product.code}</dd></div>{product.status&&<div><dt>Catalogue update</dt><dd>{titleCase(product.status)}</dd></div>}</dl><p className="fine-print">Availability and pack configuration confirmed with your quote.</p><Quantity product={product}/></div></div></Modal>}</>;
}
